### ISSUE TITLE
When Calliope mini is in DFU mode the connection icon turns red

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-flash-app-iOS#17]
When the app tries to flash a file to the Calliope mini and sets it to DFU mode the connection icon (on the right upper corner) turns red and stays so until it can reconnect to the Calliope mini. The icon should stay red to indicate everything is ok, or it should disappear while flashing data.

**Comment by januschke-itestra** [comment]
Some thoughts regarding this issue: Connection Icon should not be red, and possibly indicate that the Calliope is transferring data, possibly through a new Color (Pink?) and Symbol? Alternatively hiding it is also an option, and might be easier to implement.

**Comment by TAKeanice** [comment]
Recoloring is the same effort as hiding.

**Comment by januschke-itestra** [comment]
Symbol now stays green while flashing.
