### ISSUE TITLE
Successful connection and LED-matrix view

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-flash-app-iOS#18]
After successful connection the LED-matrix view within the app should decrease to the icon view as sometimes user forgot to actively touch the icon so the matrix overlays content. Maybe this can be done when DFU-mode starts on the Calliope mini (in combination with issue [#17).](https://github.com/calliope-mini/calliope-mini-flash-app-iOS/issues/17)

**Comment by karge-itestra** [comment]
Sounds doable, we should just hide the matrix behind the connection button right after the connection was established

**Comment by joernalraun** [comment]
Done!
