### ISSUE TITLE
Instead of the previous Hex-Files menu to select them/USB connection

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-flash-app-iOS#20]
It would be good to rather have a menu pointing to the content of the Calliope mini folder and make use of the new space to implement a USB-connection/USB-file copying option (so that a file can be copied via USB to the mini by selecting it).

**Comment by joernalraun** [comment]
Before flashing via bluetooth there could be a semi-permament question, that asks how the user wants to send the file (via USB or Bluetooth).

**Comment by joernalraun** [comment]
On DAPLink devices copying files end in an iOS copy Error.
Some old infos are here (have not been solved in DAPLink, so maybe the way though iOS/MFi could work): https://github.com/ARMmbed/DAPLink/issues/708

**Comment by januschke-itestra** [comment]
USB Flashing is now implemented, as mentioned in #42
