### ISSUE TITLE
Program already transferred

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-flash-app-iOS#23]
Currently the error "Übertragung fehlgeschlagen Keine Änderung zu übertragen" is running also if the program has not been transferred correctly. It would be better to change the headline to "Keine Änderung zu übertragen" and to have another option to chose "Trotzdem übertragen", as this also helps if you want to transfer it for whatever reason.

**Comment by Amerlander** [comment]
![image](https://github.com/calliope-edu/calliope-mini-flash-app-iOS/assets/3764089/0a3d7eab-f277-4474-83d3-62cbf93cac2e)

**Comment by TAKeanice** [comment]
Additionally, the layout looks broken. We'll fix both.

**Comment by joernalraun** [comment]
I think this is completed.
