### ISSUE TITLE
Flashing einen Schritt kürzer machen

### ISSUE THREAD

**Issue by karge-itestra** [calliope-edu/calliope-mini-flash-app-iOS#27]
Bei der Android App wird vor dem Flashen nicht noch einmal gefragt. Wenn der Nutzer eine Aktion auslöst, die wahrscheinlich auch Flashen beinhalten soll (Programm herunterladen, auf Upload klicken) soll das Programm einfach geflasht werden. Der aktuelle Dialog (möchtest du das Programm flashen) soll ausgebaut werden

**Comment by joernalraun** [comment]
Kann dies geschlossen werden? Ich meine es ist nun so integriert oder?
