### ISSUE TITLE
Autoconnect wieder einführen

### ISSUE THREAD

**Issue by TAKeanice** [calliope-edu/calliope-mini-flash-app-iOS#29]
Im Zuge der Experimente mit dem Calliope V3 haben wir das Autoconnect-Feature deaktiviert. Ein bereits eingestellter, bekannter Calliope wird nicht mehr automatisch verbunden sobald er entdeckt wurde. Wir müssen das wieder einführen sobald der Calliope V3 korrekt über Bluetooth geflashed werden kann.

**Comment by joernalraun** [comment]
Ja! Vielleicht sollte man es aber umdrehen d.h. Autoconnect nur, wenn dies aktiviert worden ist. In Schulen wechseln häufig die Geräte und da kann es hinderlich sein, wenn dieses Feature an ist, privat macht es durchaus sinn!
–> Vielleicht könnte man auch eine 3. default-Version integrieren, die bis zum Schließen der App die Verbindung hält? Das wäre vermutlich auch in Schulen sehr gut...

**Comment by joernalraun** [comment]
Aktuell ist es wieder aktiviert, die Idee (https://github.com/calliope-edu/calliope-mini-flash-app-iOS/issues/29#issuecomment-1794440963) kann von meiner Seite aus zu einem späteren Zeitpunkt nochmal diskutiert werden.

**Comment by TAKeanice** [comment]
Dann sollten wir dafür gerne ein Issue anlegen, autoconnect ist jetzt nur in dem Sinne aktiv wie es ganz früher war, nämlich dass ein bereits einmal verbundener Calliope jetzt wieder verbunden wird solange er sich nicht selbst einmal disconnected (durch Ausschalten zum Beispiel). Ich denke das Feature sollte dafür sorgen dass man die Matrix gar nicht mehr öffnen muss wenn ein bekannter Calliope erneut gefunden wird, richtig?
