### ISSUE TITLE
LED-Matrix Muster

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-flash-app-iOS#31]
Wenn man das Muster auf einem iPhone (auf dem iPad noch nicht getestet) eingegeben hat, dann verschwindet zwar die Eingabe, man kann aber nicht direkt auf das MakeCode Icon drücken. Es geht dann immer zuerst wieder das Muster auf. Wenn man es dann geschlossen hat, kann man auch auf das MakeCode Icon drücken und kommt in den Editor.
Wenn das Muster stimmt, bleibt die Touch-Area anscheinend erhalten. Wenn das Muster eingegeben ist und man es nicht ändert, dann funktioniert es direkt.

**Comment by TAKeanice** [comment]
Das müsste in der aktuellen TestFlight Version eigentlich behoben sein.

**Comment by joernalraun** [comment]
Super, habe ich zwar schon installiert, aber noch nicht getestet.
