### ISSUE TITLE
Sicherstellen, dass nur eine korrekte Datei geflasht werden kann

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-flash-app-iOS#32]
Damit man keine Probleme nach einer falschen Hardwareauswahl bekommt, wäre ein check gut, ob die Datei (oder ein Teil, bei einer Universal-Hex) auf das jeweilige Gerät gespielt werden kann/darf.

**Comment by januschke-itestra** [comment]
Added with last update - alert shows up if a incompatible hex file is flashed
