### ISSUE TITLE
Reihenfolge/Anordnung der Editoren Ändern

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-flash-app-iOS#39]
Als erstes oberstes sollte MakeCode stehen, da aktuell nur dieser den Calliope mini 3 unterstützt. Vielleicht kann man den Button auch noch stärker hervorheben? Darunter sollte dann Python kommen (iPad) und dann Open Roberta...

**Comment by januschke-itestra** [comment]
MakeCode wurde in der Reihenfolge an die erste Stelle geschoben
