### ISSUE TITLE
Text ist noch alt

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-flash-app-iOS#43]
Ein kleiner Text-Fehler ist noch in der App, wenn man eine "Demo-Datei" laden möchte. Es soll ja immer "Calliope mini" überall stehen und dort fehlt noch das "mini".

![IMG_0287](https://github.com/calliope-edu/calliope-mini-flash-app-iOS/assets/14014852/1e5a2815-24d6-4fe5-9f51-0fd51d7646f5)

**Comment by januschke-itestra** [comment]
Ist angepasst, habe noch den Standardnamen des Programms von "Das Programm" zu "das Programm" angepasst.
