### ISSUE TITLE
Integration of Open Roberta für Calliope mini 3

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-flash-app-iOS#47]
Open Roberta Link, öffnet sich Info zu neuer Version (Programmiere Calliope mini V1/V2 oder Calliope mini V3) – die Version für den V3 gibt eine andere Hex-Datei aus, als die bisherige (MicroPython-Build, ähnlich der vom https://python.calliope.cc Editor)! Dies kann man unter http://dev.open-roberta.org/ bzw. https://lab.open-roberta.org/ testen (Calliope mini V3 auswählen). Die zweite URL (für den Calliope mini V3) lautet:
https://lab.open-roberta.org/?loadSystem=calliopev3

Es wäre wohl gut, wenn nach dem Click auf das Open Roberta Bild erstmal ein Pop-Up auftauchen mit der anfrage nach dem gewünschten Editor und Auswahl-Button ('Calliope mini Version', darunter dann V1/V2 und als zweiten Button V3), die dann auf die jeweiligen Links geht (V1/V2 ist wie bisher)...

**Comment by TAKeanice** [comment]
Damit das Öffnen der Editoren einheitlich ist würde ich vorschlagen, entweder den OpenRoberta Editor doppelt anzuzeigen mit V1/2 und V3 Icon in der Grafik, oder eine Website mit Weiterleitung zu bauen, die diese Auswahl erlaubt

**Comment by joernalraun** [comment]
Alles klar, dann werden wir diese Webseite (https://calliope.cc/programmieren/editoren/open-roberta) mit der Funktion umbauen!

**Comment by joernalraun** [comment]
Updated with new URL. Already pointing to the correct editor versions. cc @januschke-itestra

**Comment by joernalraun** [comment]
> Alles klar, dann werden wir diese Webseite (http://app.calliope.cc/ios/openroberta/) mit der Funktion umbauen!

@kotchourko-itestra hier ist die Seite, die nach dem Touch auf das Open Roberta Icon geöffnet werden soll, damit man sich das die richtige Editorversion aussuchen kann. Geht das so?
