### ISSUE TITLE
Aktueller build: Icons, Buttons auf iPhone und iPad nicht korrekt

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-flash-app-iOS#48]
Die Buttons auf dem iPhone sind aktuell nicht korrekt:
![IMG_9177](https://github.com/calliope-edu/calliope-mini-flash-app-iOS/assets/14014852/43edeff9-64ff-4e6d-90b1-deecf8cd2b18)
![IMG_9176](https://github.com/calliope-edu/calliope-mini-flash-app-iOS/assets/14014852/a8d6efbf-ad12-410c-ad48-c740e1e58b41)
![IMG_9175](https://github.com/calliope-edu/calliope-mini-flash-app-iOS/assets/14014852/e93516fb-56c0-455e-903f-228de411e626)
Scan icon Größe auf dem iPad (und iPhone) ist jetzt zu sehr skaliert:
![Bildschirmfoto 2024-07-11 um 17 18 06](https://github.com/calliope-edu/calliope-mini-flash-app-iOS/assets/14014852/5f4f6fcd-4394-4fa1-ae95-de9e113cc674)
@januschke-itestra

**Comment by januschke-itestra** [comment]
Fixed on Project/Sensor View and Editors/Programs View, testing of Project Details View still necessary

**Comment by joernalraun** [comment]
Vielleicht könnte man den Punkt Hilfe rausnehmen und auf eine Kachel in der Startseite setzen? Dann hätte man unten in der Navigationsleiste mehr Platz.
Außerdem verschwindet der rechte Button bei kleinen iPhones manchmal, es bleibt aber eine aktive Fläche. Wird diese gedrückt, wird der Screen schwarz.

**Comment by joernalraun** [comment]
Im neusten Build ist die Navigation beim iPad nach oben gerutscht und beim iPhone rutscht nach dem Touch der Button rechts nach links.

![IMG_0357](https://github.com/user-attachments/assets/693c3dc3-fdbe-4e51-b1c1-422a7bef2b03)

https://github.com/user-attachments/assets/144449bb-1b08-472c-a7e4-d79853c5a4ac

**Comment by joernalraun** [comment]
Auf der Startseite steht noch "Programming with the iPad", das sollte "Programmieren mit dem iPad" in der deutschen Version heißen und nur "Programming with the iPad" auf dem englischen iOS. Sollte das zu Kang sein, bitte "Calliope mini x iPad" nehmen.
