### ISSUE TITLE
Eigener BLE UART-DIenst wird nicht angezeigt

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-flash-app-iOS#49]
Hier sollte eigentlich ein Wert ankommen:
![IMG_0340 2](https://github.com/calliope-edu/calliope-mini-flash-app-iOS/assets/14014852/f12f135f-bd89-4e01-81e3-c0ee53c514e9)
@januschke-itestra

**Comment by januschke-itestra** [comment]
Werden hier nie Daten angezeigt? In welcher Form werden die Daten über UART gesendet? - Könntest du mir vielleicht die zugehörige HEX File zukommen lassen?
