### ISSUE TITLE
Startview Bild austauschen

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-flash-app-iOS#56]
Bitte eins der beiden angehängten Bilder für die "Hallo"-Kachel nutzen. Je nachdem, welches besser zu nutzen ist (sag/png bzw. mit oder ohne Hintergrund).

Die Bildunterschrift soll nun wie folgt lauten:
Text: Programmieren mit dem iPad
Falls zu lang:
DE:Starten mit dem iPad
EN: Code with the iPad
URL: wie gehabt

![calliope_app_kachel_fix_transparent](https://github.com/user-attachments/assets/a6e6b7fd-cf85-4545-99d2-b35c4e46cbe7)
![calliope_app_kachel_fix_e5007e](https://github.com/user-attachments/assets/365e7a28-cb53-4247-b1ee-94b916b56928)
![calliope_app_kachel_fix_transparent](https://github.com/user-attachments/assets/fb909b7b-fa70-444a-9c6a-21ad039e2335)
![calliope_app_kachel_fix_e5007e](https://github.com/user-attachments/assets/b147eff6-5caa-471a-a53b-8c7cafda0b37)

**Comment by TAKeanice** [comment]
Habt ihr jetzt überall, auch auf dem iPhone, in der Startkachel den Text mit "iPad" stehen?

**Comment by joernalraun** [comment]
> Habt ihr jetzt überall, auch auf dem iPhone, in der Startkachel den Text mit "iPad" stehen?

Stimmt! Allerdings sind das auch Tipps für die iPad-Klassen (90% der Downloads). Deshalb ist das schon ok. Das ist auf der Webseite auch so…
