### ISSUE TITLE
Sensordaten-View

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/calliope-mini-flash-app-iOS#59]
Der Sensordatenview macht zumindest auf dem iPhone noch ein paar Probleme.
Das Pairingicon verschwindet, wenn man ihn nutzt und wieder verlässt und in einem anderen View ist. Er kommt dann auch nicht wieder.
Auf einem iPhone 12 kann man die Ansicht auch leider nicht nutzen (siehe Screenshot), weil der Menüpunkt nicht auswahlbar ist.

![IMG_7152](https://github.com/user-attachments/assets/e589b36f-5272-46cc-b790-96332d5a636c)

**Comment by joernalraun** [comment]
Jetzt ist die Box irgendwie zu lang... ;)
iPhone 15
![Bildschirmfoto 2024-10-15 um 14 57 18](https://github.com/user-attachments/assets/c0f14583-3235-46a5-b880-c81c075ee3f5)

**Comment by joernalraun** [comment]
Auf der iPad (Air 4) dafür zu klein...
![IMG_0376](https://github.com/user-attachments/assets/266a01df-7e79-483f-ae04-adb97f70ccdc)

**Comment by kotchourko-itestra** [comment]
363715c7b3a5a828d3995f4bbbd0130ab46f57af

0e6bf9642dcc9f10f8163e774896110d3d20b7e9

**Comment by joernalraun** [comment]
Der Sensordaten-View kann auf einem iPad mit iOS 17 nicht geöffnet werden. Fehlermeldung: Failed to insert project: SQLite error 19: FOREIGN KEY constraint failed - while executing INSERT INTO "charts" ("id", "sensorType", "projectsId") VALUES (?,?,?)

**Comment by kotchourko-itestra** [comment]
Moved to #61
